pacman: font.o pacman.o raster.o rast_asm.o splash.o map.o sprites.o events.o model.o renderer.o input.o
	cc68x -g pacman.o raster.o rast_asm.o font.o splash.o map.o sprites.o events.o model.o renderer.o input.o -o pacman

events.o: events.c raster.h
	cc68x -g -c events.c

pacman.o: pacman.c raster.h 
	cc68x -g -c pacman.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

font.o: font.c raster.h
	cc68x -g -c font.c

splash.o: splash.c raster.h
	cc68x -g -c splash.c

model.o: model.c raster.h
	cc68x -g -c model.c

map.o: map.c raster.h
	cc68x -g -c map.c

input.o: input.c raster.h
	cc68x -g -c input.c

renderer.o: renderer.c raster.h
	cc68x -g -c renderer.c

maze_array.o: maze_array.c raster.h
	cc68x -g -c maze_array.c

sprites.o: sprites.c raster.h
	cc68x -g -c sprites.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s




